Honesty-Humility:
  - humble
  - arrogant

Emotionality:
  - vulnerable
  - resilient

Extraversion:
  - outgoing
  - withdrawn

Agreeableness:
  - forgiving
  - critical

Conscientiousness:
  - diligent
  - careless

Openness-to-Experience:
  - curious
  - conventional
