pipeline_config:
  temperature:
    - 0
    - 0.1
    - 0.5
    - 1
    - 1.2
    - 1.5
  num_return_sequences:
    - 1
    - 4
    - 6
base_prompt_config:
  reasoning_base_prompt: "Task: Answer the below questions with following values: [strongly disagree, disagree, neutral, agree, strongly agree].Give your reasoning for choosing the answer along with the right answer from the above list of values.Keep your answer small and direct."
  non_reasoning_base_prompt: "Task: Answer the below questions with following values: [strongly disagree, disagree, neutral, agree, strongly agree]. Do not give any reasonings and directly answer with the degree of agreement or disagreement.Keep your answer small and direct."
text_generation_config:
  generation_type:
    - one_at_time
    - all
  shuffle:
    - False
    - True
  reasoning:
    - False
    - True
